openapi: "3.0.3"
info:
  description: "This project provides endpoints for creating persons"
  version: "@project.version@"
  title: "Person API"


paths:
  /person:
    post:
      summary: "create a person with necessary info"
      operationId: "createPerson"
      tags:
        - "Person"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDTO'
      responses:
        "200":
          description: "The Person"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonDTO"

components:
  schemas:
    PersonDTO:
      type: object
      x-class-extra-annotation: '@DriverAgeValidation'
      required: [ name, birthDate, has_driver_license ]
      properties:
        name:
          type: string
          x-field-extra-annotation: '@NotEmpty'
        birthDate:
          x-field-extra-annotation: '@BirthDateInThePast'
          type: string
          format: date
        has_driver_license:
          type: boolean