server:
  port: ${SERVER_PORT:8080}
management:
  health:
    binders:
      enabled: true
  endpoint:
    include: health,info,metrics,prometheus

spring:
  web:
    locale: en_US
  application:
    name: openapi-generator-custom-validation

springdoc:
  swagger-ui:
    path: swagger-ui.html
